-- 안전진단 입찰 모니터 — Supabase 초기 스키마
-- 한 번만 실행: Supabase 콘솔 → SQL Editor → 붙여넣기 → Run

-- ============ 1. bids: 수집된 공고 ============
create table if not exists public.bids (
    notice_id        text primary key,
    site_name        text not null,
    title            text not null,
    org              text,
    posted_at        timestamptz,
    deadline_at      timestamptz,
    url              text,
    estimated_price  bigint,
    region           text,
    matched_keywords jsonb,
    body_excerpt     text,
    category         text,
    fetched_at       timestamptz not null default now(),
    notified         boolean not null default false
);

create index if not exists idx_bids_posted_at on public.bids (posted_at desc);
create index if not exists idx_bids_deadline  on public.bids (deadline_at);
create index if not exists idx_bids_notified  on public.bids (notified);
create index if not exists idx_bids_site_name on public.bids (site_name);

-- ============ 2. sites: 발주청 명부 + 크롤링 설정 ============
create table if not exists public.sites (
    id                          bigint generated by default as identity primary key,
    name                        text unique not null,
    enabled                     boolean not null default false,
    region                      text default '',
    -- 영업 메타데이터
    category                    text default '',
    last_updated                date,
    homecheck                   text default '',
    hansijin                    text default '',
    hanjugum                    text default '',
    bidding_status              text default '',
    new_submission_date         date,
    period_start                date,
    period_end                  date,
    announce_planned_date       date,
    previous_announce_date      date,
    previous_deadline           date,
    under_100m_winner_method    text default '',
    note                        text default '',
    -- 크롤링 설정
    adapter                     text default 'egov',
    base_url                    text default '',
    list_url                    text default '',
    list_params                 jsonb default '{}'::jsonb,
    pagination                  jsonb default '{}'::jsonb,
    selectors                   jsonb default '{}'::jsonb,
    created_at                  timestamptz not null default now(),
    updated_at                  timestamptz not null default now()
);

-- ============ 3. keywords: 필터 키워드 ============
create table if not exists public.keywords (
    id          bigint generated by default as identity primary key,
    kind        text not null check (kind in ('include','exclude','match_in')),
    value       text not null,
    created_at  timestamptz not null default now()
);

create unique index if not exists idx_keywords_unique on public.keywords (kind, value);

-- ============ 4. app_users: 대시보드 로그인 사용자 ============
create table if not exists public.app_users (
    username       text primary key,
    password_hash  text not null,
    name           text default '',
    email          text default '',
    role           text not null default 'viewer' check (role in ('admin','viewer')),
    categories     text[] default '{}',
    created_at     timestamptz not null default now(),
    updated_at     timestamptz not null default now()
);

-- ============ updated_at 자동 갱신 트리거 ============
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_sites_updated_at on public.sites;
create trigger trg_sites_updated_at
    before update on public.sites
    for each row execute function public.set_updated_at();

drop trigger if exists trg_app_users_updated_at on public.app_users;
create trigger trg_app_users_updated_at
    before update on public.app_users
    for each row execute function public.set_updated_at();

-- ============ Row Level Security ============
-- service_role 키는 RLS를 우회하므로 자동 통과 (cron·서버사이드 모니터링용).
-- anon 키는 정책이 없으면 자동 거부 — 브라우저에 노출돼도 안전.
-- 우리 Streamlit 앱은 service_role 키를 서버 환경변수로 사용.

alter table public.bids      enable row level security;
alter table public.sites     enable row level security;
alter table public.keywords  enable row level security;
alter table public.app_users enable row level security;
