-- ============================================================
-- 안전진단 크롤러 → 허브 Supabase 이관용 통합 DDL
-- migrations/001 + 002 + 003 을 순서대로 합친 것 (1회 실행)
--
-- 실행 위치: 허브 Supabase 콘솔 → SQL Editor → 붙여넣기 → Run
-- (서비스 키로는 DDL 실행 불가라 콘솔에서 실행해야 함)
--
-- 생성 테이블: bids / sites / keywords / app_users
-- 허브에 동명 테이블이 없음을 확인한 상태이며, 전부 IF NOT EXISTS라 재실행해도 안전.
-- ============================================================

-- ============ 1. bids: 수집된 공고 ============
create table if not exists public.bids (
    notice_id        text primary key,
    site_name        text not null,
    title            text not null,
    org              text,
    posted_at        timestamptz,
    deadline_at      timestamptz,
    url              text,
    estimated_price  bigint,
    region           text,
    matched_keywords jsonb,
    body_excerpt     text,
    category         text,
    fetched_at       timestamptz not null default now(),
    notified         boolean not null default false
);

create index if not exists idx_bids_posted_at on public.bids (posted_at desc);
create index if not exists idx_bids_deadline  on public.bids (deadline_at);
create index if not exists idx_bids_notified  on public.bids (notified);
create index if not exists idx_bids_site_name on public.bids (site_name);

-- ============ 2. sites: 발주청 명부 + 크롤링 설정 ============
create table if not exists public.sites (
    id                          bigint generated by default as identity primary key,
    name                        text unique not null,
    enabled                     boolean not null default false,
    region                      text default '',
    -- 영업 메타데이터
    category                    text default '',
    last_updated                date,
    homecheck                   text default '',
    hansijin                    text default '',
    hanjugum                    text default '',
    bidding_status              text default '',
    new_submission_date         date,
    period_start                date,
    period_end                  date,
    announce_planned_date       date,
    previous_announce_date      date,
    previous_deadline           date,
    under_100m_winner_method    text default '',
    note                        text default '',
    -- 크롤링 설정
    adapter                     text default 'egov',
    base_url                    text default '',
    list_url                    text default '',
    list_params                 jsonb default '{}'::jsonb,
    pagination                  jsonb default '{}'::jsonb,
    selectors                   jsonb default '{}'::jsonb,
    created_at                  timestamptz not null default now(),
    updated_at                  timestamptz not null default now()
);

-- ============ 3. keywords: 필터 키워드 ============
create table if not exists public.keywords (
    id          bigint generated by default as identity primary key,
    kind        text not null check (kind in ('include','exclude','match_in')),
    value       text not null,
    created_at  timestamptz not null default now()
);

create unique index if not exists idx_keywords_unique on public.keywords (kind, value);

-- ============ 4. app_users: 대시보드 로그인 사용자 ============
create table if not exists public.app_users (
    username       text primary key,
    password_hash  text not null,
    name           text default '',
    email          text default '',
    role           text not null default 'viewer' check (role in ('admin','viewer')),
    categories     text[] default '{}',
    created_at     timestamptz not null default now(),
    updated_at     timestamptz not null default now()
);

-- ============ updated_at 자동 갱신 트리거 ============
-- 주의: set_updated_at() 함수명이 허브에 이미 있으면 create or replace로 덮어씀.
-- 본문이 동일한 표준 패턴이라 기존 동작에 영향 없음.
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_sites_updated_at on public.sites;
create trigger trg_sites_updated_at
    before update on public.sites
    for each row execute function public.set_updated_at();

drop trigger if exists trg_app_users_updated_at on public.app_users;
create trigger trg_app_users_updated_at
    before update on public.app_users
    for each row execute function public.set_updated_at();

-- ============ 002: sites 영업 메타데이터 4개 컬럼 ============
alter table public.sites
    add column if not exists above_100m_winner_method  text default '',
    add column if not exists bid_submission_method     text default '',
    add column if not exists performance_proof         text default '',
    add column if not exists work_overlap_doc          text default '';

-- ============ 003: bids LLM 추출 결과(JSONB) ============
alter table public.bids
    add column if not exists extracted_fields jsonb default null;

create index if not exists idx_bids_has_extracted on public.bids ((extracted_fields is not null));

-- ============ Row Level Security ============
-- 정책 없음 = 서비스롤 전용 (허브 sales_cache와 같은 패턴).
-- anon/publishable 키로는 접근 불가 — 브라우저 노출돼도 안전.
ALTER TABLE bids      ENABLE ROW LEVEL SECURITY;
ALTER TABLE sites     ENABLE ROW LEVEL SECURITY;
ALTER TABLE keywords  ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_users ENABLE ROW LEVEL SECURITY;
